name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install cmake
          pip install conan
          conan profile detect --force
          
      - name: Build 
        shell: bash
        run: |
          make build
