name: Release
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  check_version:
    runs-on: ubuntu-latest
    outputs:
      are_versions_different: ${{ steps.compare_versions.outputs.are_versions_different }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current repository tag
        id: current_tag
        run: |
          git fetch --prune --unshallow 
          echo "TAG=$(git describe --abbrev=0 --tags --always)" >> $GITHUB_OUTPUT
      
      - name: Extract project version
        id: current_version
        run: |
          echo "VERSION=$(grep -oP 'project\(.*VERSION \K[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt)" >> $GITHUB_OUTPUT
      
      - name: Compare versions
        id: compare_versions
        run: |
          if [ "${{ steps.current_version.outputs.version }}" == "${{ steps.current_tag.outputs.tag }}" ]; then
            echo "ARE_VERSIONS_DIFFERENT=false" >> $GITHUB_OUTPUT 
          else
            echo "ARE_VERSIONS_DIFFERENT=true" >> $GITHUB_OUTPUT 
          fi
          
  release:
    needs: check_version
    if: needs.check_version.outputs.are_versions_different == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install cmake
          pip install conan
          conan profile detect --force
          
      - name: Build and install 
        shell: bash
        run: |
          make install INSTALL_PREFIX=$(pwd)/install

      - name: Extract project version
        id: version
        run: |
          echo "VERSION=$(grep -oP 'project\(.*VERSION \K[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt)" >> $GITHUB_OUTPUT
        
      - name: Name artifact
        id: artifact
        run: |
          echo "artifact=yabp-${{ steps.version.outputs.version }}.tar.gz" >> $GITHUB_ENV
      
      - name: Pack files
        id: pack
        run: |
          tar zcvf ${{ env.artifact }} -C$(pwd)/ install/
      
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          path: ./${{ env.artifact }}
          name: ${{ env.artifact }}

      - name: Publish artifact
        uses: softprops/action-gh-release@v1
        with:
         tag_name: ${{ steps.version.outputs.version }}
         files: |
          ${{ env.artifact }}
